apiVersion: v1
kind: Service
metadata:
  name: issue-service
  labels:
    k8s-app: kube-dns
spec:
  selector:
    app: issue
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: issuehistory-service
  labels:
    k8s-app: kube-dns
spec:
  selector:
    app: issuehistory
  ports:
    - port: 3000
      targetPort: 3000
